server:
  port: ${APPLICATION_PORT}

spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB

  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_HOST}/auth/realms/${KEYCLOAK_REALM}

cloud:
  server:
    name: ${CLOUD_HOST}
    download-url: ${CLOUD_DOWNLOAD_URL}
    username: ${CLOUD_USERNAME}
    password: ${CLOUD_PASSWORD}

keycloak:
  resource: ${KEYCLOAK_CLIENT_ID}
  allowed-origin: ${ALLOWED_ORIGIN}

realm-admin:
  server-url: ${KEYCLOAK_HOST}/auth
  realm: ${KEYCLOAK_REALM}
  client-id: admin-cli
  username: ${KEYCLOAK_ADMIN_USER}
  password: ${KEYCLOAK_ADMIN_PSWD}


