server:
  port: 8090

spring:
  profiles:
    active: dev
  datasource:
    password: mysecretpassword
    url: jdbc:mysql://localhost:3306/agrisud_elearning
    username: root

  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB

  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:3800/auth/realms/agrisud

cloud:
  server:
    name: http://localhost:3900
    password: cloudagrisudcrud
    username: cloudagrisudcrud

keycloak:
  resource: agrisud-elearning-api
  allowed-origin: http://localhost:3000

realm-admin:
  server-url: http://localhost:3800/auth
  realm: agrisud
  client-id: admin-cli
  username: agrisud-admin
  password: mysecretpassword


